// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assistant_suggestions.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssistantSuggestions = `-- name: CreateAssistantSuggestions :one
INSERT INTO assistant_suggestions(day_session_id, message, status)
VALUES($1, $2, $3)
RETURNING id, day_session_id, message, status, created_at
`

type CreateAssistantSuggestionsParams struct {
	DaySessionID pgtype.UUID `json:"day_session_id"`
	Message      string      `json:"message"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateAssistantSuggestions(ctx context.Context, arg CreateAssistantSuggestionsParams) (AssistantSuggestion, error) {
	row := q.db.QueryRow(ctx, createAssistantSuggestions, arg.DaySessionID, arg.Message, arg.Status)
	var i AssistantSuggestion
	err := row.Scan(
		&i.ID,
		&i.DaySessionID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const editAssistantSuggestion = `-- name: EditAssistantSuggestion :one
UPDATE assistant_suggestions
SET
    message = $2,
    status = $3
WHERE id = $1
RETURNING id, day_session_id, message, status, created_at
`

type EditAssistantSuggestionParams struct {
	ID      pgtype.UUID `json:"id"`
	Message string      `json:"message"`
	Status  string      `json:"status"`
}

func (q *Queries) EditAssistantSuggestion(ctx context.Context, arg EditAssistantSuggestionParams) (AssistantSuggestion, error) {
	row := q.db.QueryRow(ctx, editAssistantSuggestion, arg.ID, arg.Message, arg.Status)
	var i AssistantSuggestion
	err := row.Scan(
		&i.ID,
		&i.DaySessionID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAssistantSuggestions = `-- name: GetAssistantSuggestions :many
SELECT id, day_session_id, message, status, created_at
FROM assistant_suggestions
WHERE day_session_id = $1
`

func (q *Queries) GetAssistantSuggestions(ctx context.Context, daySessionID pgtype.UUID) ([]AssistantSuggestion, error) {
	rows, err := q.db.Query(ctx, getAssistantSuggestions, daySessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistantSuggestion
	for rows.Next() {
		var i AssistantSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.DaySessionID,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
