// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Trip struct {
	ID             pgtype.UUID        `json:"id"`
	Destination    string             `json:"destination"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	TravelersCount int32              `json:"travelers_count"`
	Pace           pgtype.Text        `json:"pace"`
	InterestsJson  []byte             `json:"interests_json"`
	DiningJson     []byte             `json:"dining_json"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
