// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trip.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (destination, start_date, end_date, travelers_count)
VALUES($1,$2,$3,$4)
RETURNING id, destination,start_date, end_date, travelers_count, created_at
`

type CreateTripParams struct {
	Destination    string      `json:"destination"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	TravelersCount int32       `json:"travelers_count"`
}

type CreateTripRow struct {
	ID             pgtype.UUID        `json:"id"`
	Destination    string             `json:"destination"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	TravelersCount int32              `json:"travelers_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (CreateTripRow, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.Destination,
		arg.StartDate,
		arg.EndDate,
		arg.TravelersCount,
	)
	var i CreateTripRow
	err := row.Scan(
		&i.ID,
		&i.Destination,
		&i.StartDate,
		&i.EndDate,
		&i.TravelersCount,
		&i.CreatedAt,
	)
	return i, err
}

const listTrips = `-- name: ListTrips :many
SELECT id, destination, start_date, end_date, travelers_count, created_at
FROM trips
ORDER BY created_at DESC
`

type ListTripsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Destination    string             `json:"destination"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	TravelersCount int32              `json:"travelers_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTrips(ctx context.Context) ([]ListTripsRow, error) {
	rows, err := q.db.Query(ctx, listTrips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripsRow
	for rows.Next() {
		var i ListTripsRow
		if err := rows.Scan(
			&i.ID,
			&i.Destination,
			&i.StartDate,
			&i.EndDate,
			&i.TravelersCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
