// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvents = `-- name: CreateEvents :one
INSERT INTO events(day_session_id, type, ts, payload_json)
VALUES($1,$2,$3,$4)
RETURNING id, day_session_id, type, ts, payload_json, created_at
`

type CreateEventsParams struct {
	DaySessionID pgtype.UUID        `json:"day_session_id"`
	Type         string             `json:"type"`
	Ts           pgtype.Timestamptz `json:"ts"`
	PayloadJson  []byte             `json:"payload_json"`
}

func (q *Queries) CreateEvents(ctx context.Context, arg CreateEventsParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvents,
		arg.DaySessionID,
		arg.Type,
		arg.Ts,
		arg.PayloadJson,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.DaySessionID,
		&i.Type,
		&i.Ts,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const getEvents = `-- name: GetEvents :many
SELECT id, day_session_id, type, ts, payload_json, created_at
FROM events
WHERE day_session_id=$1
ORDER BY created_at DESC
`

func (q *Queries) GetEvents(ctx context.Context, daySessionID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEvents, daySessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.DaySessionID,
			&i.Type,
			&i.Ts,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
