// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan_stop.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlanStop = `-- name: CreatePlanStop :one
INSERT INTO plan_stops (
    plan_version_id,
    position,
    title,
    category_label,
    image_url,
    planned_arrival,
    planned_departure,
    travel_minutes,
    stay_minutes,
    busy_risk_label
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING
    id,
    plan_version_id,
    position,
    title,
    category_label,
    image_url,
    planned_arrival,
    planned_departure,
    travel_minutes,
    stay_minutes,
    busy_risk_label,
    created_at
`

type CreatePlanStopParams struct {
	PlanVersionID    pgtype.UUID        `json:"plan_version_id"`
	Position         int32              `json:"position"`
	Title            string             `json:"title"`
	CategoryLabel    string             `json:"category_label"`
	ImageUrl         pgtype.Text        `json:"image_url"`
	PlannedArrival   pgtype.Timestamptz `json:"planned_arrival"`
	PlannedDeparture pgtype.Timestamptz `json:"planned_departure"`
	TravelMinutes    int32              `json:"travel_minutes"`
	StayMinutes      int32              `json:"stay_minutes"`
	BusyRiskLabel    string             `json:"busy_risk_label"`
}

func (q *Queries) CreatePlanStop(ctx context.Context, arg CreatePlanStopParams) (PlanStop, error) {
	row := q.db.QueryRow(ctx, createPlanStop,
		arg.PlanVersionID,
		arg.Position,
		arg.Title,
		arg.CategoryLabel,
		arg.ImageUrl,
		arg.PlannedArrival,
		arg.PlannedDeparture,
		arg.TravelMinutes,
		arg.StayMinutes,
		arg.BusyRiskLabel,
	)
	var i PlanStop
	err := row.Scan(
		&i.ID,
		&i.PlanVersionID,
		&i.Position,
		&i.Title,
		&i.CategoryLabel,
		&i.ImageUrl,
		&i.PlannedArrival,
		&i.PlannedDeparture,
		&i.TravelMinutes,
		&i.StayMinutes,
		&i.BusyRiskLabel,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanStopByID = `-- name: GetPlanStopByID :one
SELECT
    id,
    plan_version_id,
    position,
    title,
    category_label,
    image_url,
    planned_arrival,
    planned_departure,
    travel_minutes,
    stay_minutes,
    busy_risk_label,
    created_at
FROM plan_stops
WHERE id = $1
`

func (q *Queries) GetPlanStopByID(ctx context.Context, id pgtype.UUID) (PlanStop, error) {
	row := q.db.QueryRow(ctx, getPlanStopByID, id)
	var i PlanStop
	err := row.Scan(
		&i.ID,
		&i.PlanVersionID,
		&i.Position,
		&i.Title,
		&i.CategoryLabel,
		&i.ImageUrl,
		&i.PlannedArrival,
		&i.PlannedDeparture,
		&i.TravelMinutes,
		&i.StayMinutes,
		&i.BusyRiskLabel,
		&i.CreatedAt,
	)
	return i, err
}

const listPlanStopsByPlanVersionID = `-- name: ListPlanStopsByPlanVersionID :many
SELECT
    id,
    plan_version_id,
    position,
    title,
    category_label,
    image_url,
    planned_arrival,
    planned_departure,
    travel_minutes,
    stay_minutes,
    busy_risk_label,
    created_at
FROM plan_stops
WHERE plan_version_id = $1
ORDER BY position ASC
`

func (q *Queries) ListPlanStopsByPlanVersionID(ctx context.Context, planVersionID pgtype.UUID) ([]PlanStop, error) {
	rows, err := q.db.Query(ctx, listPlanStopsByPlanVersionID, planVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanStop
	for rows.Next() {
		var i PlanStop
		if err := rows.Scan(
			&i.ID,
			&i.PlanVersionID,
			&i.Position,
			&i.Title,
			&i.CategoryLabel,
			&i.ImageUrl,
			&i.PlannedArrival,
			&i.PlannedDeparture,
			&i.TravelMinutes,
			&i.StayMinutes,
			&i.BusyRiskLabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
