// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan_version.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlanVersion = `-- name: CreatePlanVersion :one
INSERT INTO plan_versions ( day_session_id, version, notes)
VALUES ($1, $2, $3)
RETURNING id, day_session_id, version, notes, created_at
`

type CreatePlanVersionParams struct {
	DaySessionID pgtype.UUID `json:"day_session_id"`
	Version      int32       `json:"version"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) CreatePlanVersion(ctx context.Context, arg CreatePlanVersionParams) (PlanVersion, error) {
	row := q.db.QueryRow(ctx, createPlanVersion, arg.DaySessionID, arg.Version, arg.Notes)
	var i PlanVersion
	err := row.Scan(
		&i.ID,
		&i.DaySessionID,
		&i.Version,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePlan = `-- name: GetActivePlan :one
SELECT id, day_session_id, version, notes, created_at
FROM plan_versions
WHERE day_session_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetActivePlan(ctx context.Context, daySessionID pgtype.UUID) (PlanVersion, error) {
	row := q.db.QueryRow(ctx, getActivePlan, daySessionID)
	var i PlanVersion
	err := row.Scan(
		&i.ID,
		&i.DaySessionID,
		&i.Version,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listPlanVersionsByDaySessionID = `-- name: ListPlanVersionsByDaySessionID :many
SELECT id, day_session_id, version, notes, created_at
FROM plan_versions
WHERE day_session_id = $1
ORDER BY version ASC
`

func (q *Queries) ListPlanVersionsByDaySessionID(ctx context.Context, daySessionID pgtype.UUID) ([]PlanVersion, error) {
	rows, err := q.db.Query(ctx, listPlanVersionsByDaySessionID, daySessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanVersion
	for rows.Next() {
		var i PlanVersion
		if err := rows.Scan(
			&i.ID,
			&i.DaySessionID,
			&i.Version,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
