// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daysession.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDaySession = `-- name: CreateDaySession :one
INSERT INTO day_sessions (trip_id, date, start_time,start_label)
VALUES($1, $2, $3, $4)
RETURNING id, trip_id, date, start_time, start_label, active_plan_version_id, created_at
`

type CreateDaySessionParams struct {
	TripID     pgtype.UUID `json:"trip_id"`
	Date       pgtype.Date `json:"date"`
	StartTime  string      `json:"start_time"`
	StartLabel string      `json:"start_label"`
}

type CreateDaySessionRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TripID              pgtype.UUID        `json:"trip_id"`
	Date                pgtype.Date        `json:"date"`
	StartTime           string             `json:"start_time"`
	StartLabel          string             `json:"start_label"`
	ActivePlanVersionID pgtype.UUID        `json:"active_plan_version_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDaySession(ctx context.Context, arg CreateDaySessionParams) (CreateDaySessionRow, error) {
	row := q.db.QueryRow(ctx, createDaySession,
		arg.TripID,
		arg.Date,
		arg.StartTime,
		arg.StartLabel,
	)
	var i CreateDaySessionRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Date,
		&i.StartTime,
		&i.StartLabel,
		&i.ActivePlanVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getDaySession = `-- name: GetDaySession :one
SELECT id, trip_id, date, start_time, start_label, active_plan_version_id, created_at
FROM day_sessions 
WHERE id = $1
`

type GetDaySessionRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TripID              pgtype.UUID        `json:"trip_id"`
	Date                pgtype.Date        `json:"date"`
	StartTime           string             `json:"start_time"`
	StartLabel          string             `json:"start_label"`
	ActivePlanVersionID pgtype.UUID        `json:"active_plan_version_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDaySession(ctx context.Context, id pgtype.UUID) (GetDaySessionRow, error) {
	row := q.db.QueryRow(ctx, getDaySession, id)
	var i GetDaySessionRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Date,
		&i.StartTime,
		&i.StartLabel,
		&i.ActivePlanVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const listDaySession = `-- name: ListDaySession :many
SELECT id, trip_id, date, start_time, start_label, active_plan_version_id, created_at
FROM day_sessions 
WHERE trip_id = $1
`

type ListDaySessionRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TripID              pgtype.UUID        `json:"trip_id"`
	Date                pgtype.Date        `json:"date"`
	StartTime           string             `json:"start_time"`
	StartLabel          string             `json:"start_label"`
	ActivePlanVersionID pgtype.UUID        `json:"active_plan_version_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDaySession(ctx context.Context, tripID pgtype.UUID) ([]ListDaySessionRow, error) {
	rows, err := q.db.Query(ctx, listDaySession, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDaySessionRow
	for rows.Next() {
		var i ListDaySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Date,
			&i.StartTime,
			&i.StartLabel,
			&i.ActivePlanVersionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivePlan = `-- name: UpdateActivePlan :exec
UPDATE day_sessions
SET active_plan_version_id = $2
WHERE id = $1
`

type UpdateActivePlanParams struct {
	ID                  pgtype.UUID `json:"id"`
	ActivePlanVersionID pgtype.UUID `json:"active_plan_version_id"`
}

func (q *Queries) UpdateActivePlan(ctx context.Context, arg UpdateActivePlanParams) error {
	_, err := q.db.Exec(ctx, updateActivePlan, arg.ID, arg.ActivePlanVersionID)
	return err
}
