// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daysession.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDaySession = `-- name: CreateDaySession :one
INSERT INTO day_sessions (trip_id, date, start_time,start_label)
VALUES($1, $2, $3, $4)
RETURNING id, trip_id, date, start_time, start_label, created_at
`

type CreateDaySessionParams struct {
	TripID     pgtype.UUID `json:"trip_id"`
	Date       pgtype.Date `json:"date"`
	StartTime  string      `json:"start_time"`
	StartLabel string      `json:"start_label"`
}

type CreateDaySessionRow struct {
	ID         pgtype.UUID        `json:"id"`
	TripID     pgtype.UUID        `json:"trip_id"`
	Date       pgtype.Date        `json:"date"`
	StartTime  string             `json:"start_time"`
	StartLabel string             `json:"start_label"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDaySession(ctx context.Context, arg CreateDaySessionParams) (CreateDaySessionRow, error) {
	row := q.db.QueryRow(ctx, createDaySession,
		arg.TripID,
		arg.Date,
		arg.StartTime,
		arg.StartLabel,
	)
	var i CreateDaySessionRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Date,
		&i.StartTime,
		&i.StartLabel,
		&i.CreatedAt,
	)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT id, trip_id, date, start_time, start_label, created_at
FROM day_sessions 
WHERE id= $1
`

type GetByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	TripID     pgtype.UUID        `json:"trip_id"`
	Date       pgtype.Date        `json:"date"`
	StartTime  string             `json:"start_time"`
	StartLabel string             `json:"start_label"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetByID(ctx context.Context, id pgtype.UUID) (GetByIDRow, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i GetByIDRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Date,
		&i.StartTime,
		&i.StartLabel,
		&i.CreatedAt,
	)
	return i, err
}

const getDaySessionByIDAndDate = `-- name: GetDaySessionByIDAndDate :one
SELECT id, trip_id, date, start_time, start_label, created_at
FROM day_sessions 
WHERE trip_id = $1
AND date = $2
LIMIT 1
`

type GetDaySessionByIDAndDateParams struct {
	TripID pgtype.UUID `json:"trip_id"`
	Date   pgtype.Date `json:"date"`
}

type GetDaySessionByIDAndDateRow struct {
	ID         pgtype.UUID        `json:"id"`
	TripID     pgtype.UUID        `json:"trip_id"`
	Date       pgtype.Date        `json:"date"`
	StartTime  string             `json:"start_time"`
	StartLabel string             `json:"start_label"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDaySessionByIDAndDate(ctx context.Context, arg GetDaySessionByIDAndDateParams) (GetDaySessionByIDAndDateRow, error) {
	row := q.db.QueryRow(ctx, getDaySessionByIDAndDate, arg.TripID, arg.Date)
	var i GetDaySessionByIDAndDateRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Date,
		&i.StartTime,
		&i.StartLabel,
		&i.CreatedAt,
	)
	return i, err
}
