// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DaySession struct {
	ID         pgtype.UUID        `json:"id"`
	TripID     pgtype.UUID        `json:"trip_id"`
	Date       pgtype.Date        `json:"date"`
	StartTime  string             `json:"start_time"`
	StartLabel string             `json:"start_label"`
	StartLat   pgtype.Float8      `json:"start_lat"`
	StartLon   pgtype.Float8      `json:"start_lon"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Trip struct {
	ID             pgtype.UUID        `json:"id"`
	Destination    string             `json:"destination"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	TravelersCount int32              `json:"travelers_count"`
	Pace           pgtype.Text        `json:"pace"`
	InterestsJson  []byte             `json:"interests_json"`
	DiningJson     []byte             `json:"dining_json"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
