// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DaySession struct {
	ID         pgtype.UUID        `json:"id"`
	TripID     pgtype.UUID        `json:"trip_id"`
	Date       pgtype.Date        `json:"date"`
	StartTime  string             `json:"start_time"`
	StartLabel string             `json:"start_label"`
	StartLat   pgtype.Float8      `json:"start_lat"`
	StartLon   pgtype.Float8      `json:"start_lon"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PlanStop struct {
	ID               pgtype.UUID        `json:"id"`
	PlanVersionID    pgtype.UUID        `json:"plan_version_id"`
	Position         int32              `json:"position"`
	Title            string             `json:"title"`
	CategoryLabel    string             `json:"category_label"`
	ImageUrl         pgtype.Text        `json:"image_url"`
	PlannedArrival   pgtype.Timestamptz `json:"planned_arrival"`
	PlannedDeparture pgtype.Timestamptz `json:"planned_departure"`
	TravelMinutes    int32              `json:"travel_minutes"`
	StayMinutes      int32              `json:"stay_minutes"`
	BusyRiskLabel    string             `json:"busy_risk_label"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PlanVersion struct {
	ID           pgtype.UUID        `json:"id"`
	DaySessionID pgtype.UUID        `json:"day_session_id"`
	Version      int32              `json:"version"`
	Notes        pgtype.Text        `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Trip struct {
	ID             pgtype.UUID        `json:"id"`
	Destination    string             `json:"destination"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	TravelersCount int32              `json:"travelers_count"`
	Pace           pgtype.Text        `json:"pace"`
	InterestsJson  []byte             `json:"interests_json"`
	DiningJson     []byte             `json:"dining_json"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
